//
//  MainPresenter.swift
//  CryptoCurrencyApp
//
//  Created by IT-EFW-65-03 on 21/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentDisplay(response: Main.CryptoCurrency.Response)
}

class MainPresenter: MainPresentationLogic
{
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentDisplay(response: Main.CryptoCurrency.Response)
    {  
        let viewModel = Main.CryptoCurrency.ViewModel(item: response.item, currencyItem: response.currencyItem, displayList: response.displayList)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
